---
- name: Build and Deploy ReactJS App to Docker Hub
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Debug 2  
      command: echo DOCKER_PASSWORD $DOCKER_PASSWORD

    - name: Debug DOCKER_USERNAME
      debug:
        var: DOCKER_USERNAME

    - name: Debug DOCKER_PASSWORD
      debug:
        var: DOCKER_PASSWORD
      
    - name: Checkout Repository
      git:
        repo: "https://github.com/JuliaKovtun/react_pr.git"
        dest: "react_pr"
        version: master

    - name: Set up Node.js
      community.general.npm:
        path: react_pr

    - name: Install Dependencies
      npm:
        path: react_pr
        state: present

    - name: Build React App
      command: npm run build
      args:
        chdir: react_pr

    - name: Log in to Docker Hub
      command: docker login -u "{{ DOCKER_USERNAME }}" -p "{{ DOCKER_PASSWORD }}"

    - name: Build Docker Image
      command: docker build -t juliakovtun/react_pr:latest .

    - name: Push Docker Image to DockerHub
      command: docker push juliakovtun/react_pr:latest

